/** アプリの画面の文言 (英語 / 日本語)。図の中の文言はライブラリの i18n を使う */
import type { AppLang } from "../shared";

const en = {
  appTitle: "Docx Revision Analyzer",
  open: "Open .docx…",
  dropHere: "Drop a Word file (.docx) here, or",
  dropHint:
    "Everything is analyzed on this computer. The document and its text are never sent anywhere.",
  purpose:
    "This is a tool for writers to look back on how their own document was written — not a way to police others.",
  tabChart: "Chart",
  tabFlow: "Flow",
  tabHighlights: "Highlights",
  tabSettings: "Settings",
  gap: "Split sessions at idle gaps over (hours)",
  from: "From",
  to: "To",
  bulkChars: "Bulk insertion (chars)",
  bulkCharsByRules: "Set by the rules file",
  bucket: "Time step",
  bucketAuto: "Auto",
  bucketMinute: "Minute",
  bucketHour: "Hour",
  bucketDay: "Day",
  chartSplit: "Split at idle gaps",
  saveSvg: "Save SVG",
  savePng: "Save PNG",
  saved: (p: string) => `Saved ${p}`,
  fixHistory: "Fix the settings (keeps a backup)",
  fixed: (p: string) => `Settings fixed. The original was kept as ${p}. Edits from now on will be timestamped.`,
  noFile: "No file opened",
  analyzing: "Analyzing…",
  highlightsEmpty: "No highlighted insertions in this document.",
  highlightsIntro:
    "Insertions picked out by the classifiers. Click one to show where it is in the figures. " +
    "These are hints for looking back, not proof of anything.",
  colWhen: "When",
  colCategory: "Category",
  colReason: "Why",
  colExcerpt: "Text",
  excerptDeleted: "(later deleted)",
  showInFlow: "Flow",
  showInChart: "Chart",
  settingsLang: "Language",
  langSystem: "System",
  settingsRules: "Highlight rules",
  rulesDefault: (n: number) => `Default (bulk insertion of ${n}+ chars at the same time)`,
  chooseRules: "Choose rules file…",
  clearRules: "Use the default",
  rulesError: (msg: string) => `The rules file can't be used: ${msg}`,
  settingsExtensions: "Extensions",
  extensionsNone: "No extensions are installed.",
  settingsUpdates: "Updates",
  checkForUpdates: "Check GitHub Releases for a new version at startup",
  updatesNote:
    "Only the app version is checked; no document or analysis data is sent. Updates are verified before installing.",
  updatesDevBuild: "Not available when running from source.",
  settingsAbout: "About",
  aboutText:
    "Track Changes in a .docx saved on a computer can be turned off, accepted, or rewritten (including dates and " +
    "authors), so the history shown here can be incomplete or altered. Use it to reflect on your own writing.",
  version: (v: string) => `Version ${v}`,
  error: (msg: string) => `Error: ${msg}`,
};

export type Strings = typeof en;

const ja: Strings = {
  appTitle: "Docx Revision Analyzer",
  open: ".docx を開く…",
  dropHere: "Word ファイル (.docx) をここにドロップするか、",
  dropHint: "解析はすべてこのコンピュータの中で行います。文書や本文をどこかへ送ることはありません。",
  purpose: "書き手が自分の文書の執筆過程を振り返るための道具です。他人を取り締まるためのものではありません。",
  tabChart: "チャート",
  tabFlow: "フロー",
  tabHighlights: "ハイライト",
  tabSettings: "設定",
  gap: "区間を分ける無編集期間 (時間)",
  from: "開始",
  to: "終了",
  bulkChars: "一括挿入 (文字数)",
  bulkCharsByRules: "ルールファイルで設定",
  bucket: "時間の刻み",
  bucketAuto: "自動",
  bucketMinute: "分",
  bucketHour: "時間",
  bucketDay: "日",
  chartSplit: "無編集期間で分ける",
  saveSvg: "SVG を保存",
  savePng: "PNG を保存",
  saved: (p) => `${p} に保存しました`,
  fixHistory: "設定を修正する (元のファイルは残します)",
  fixed: (p) => `設定を修正しました。元のファイルは ${p} として残しています。これからの編集には日時が記録されます。`,
  noFile: "ファイルが開かれていません",
  analyzing: "解析中…",
  highlightsEmpty: "この文書にはハイライトされた挿入はありません。",
  highlightsIntro:
    "分類器が取り上げた挿入です。クリックすると図の中の位置を示します。振り返りのための手がかりであり、何かの証拠ではありません。",
  colWhen: "日時",
  colCategory: "分類",
  colReason: "理由",
  colExcerpt: "本文",
  excerptDeleted: "(後で削除)",
  showInFlow: "フロー",
  showInChart: "チャート",
  settingsLang: "表示言語",
  langSystem: "システムに合わせる",
  settingsRules: "ハイライトの判定ルール",
  rulesDefault: (n) => `既定 (同じ時刻にまとめて ${n} 文字以上の挿入を一括挿入とする)`,
  chooseRules: "ルールファイルを選ぶ…",
  clearRules: "既定に戻す",
  rulesError: (msg) => `ルールファイルを使えません: ${msg}`,
  settingsExtensions: "拡張機能",
  extensionsNone: "インストールされている拡張機能はありません。",
  settingsUpdates: "アップデート",
  checkForUpdates: "起動時に GitHub Releases で新しいバージョンを確認する",
  updatesNote: "確認するのはアプリのバージョンだけで、文書や解析結果は送りません。更新は検証してから入れ替えます。",
  updatesDevBuild: "ソースから起動している場合は使えません。",
  settingsAbout: "このアプリについて",
  aboutText:
    "コンピュータに保存された .docx の変更履歴は、記録をオフにする・すべて承諾する・日時や作成者を書き換えるといった操作で" +
    "消したり作り替えたりできます。ここに表示される履歴は欠けていたり改変されていたりする可能性があります。" +
    "自分の執筆を振り返るために使ってください。",
  version: (v) => `バージョン ${v}`,
  error: (msg) => `エラー: ${msg}`,
};

export const STRINGS: Record<AppLang, Strings> = { en, ja };
