/** アプリの画面の文言 (英語 / 日本語)。図の中の文言はライブラリの i18n を使う */
import type { AppLang } from "../shared";

const en = {
  appTitle: "Docx Revision Analyzer",
  open: "Open .docx…",
  dropHere: "Drop a Word file (.docx) here, or",
  dropHint:
    "Everything is analyzed on this computer. The document and its text are never sent anywhere.",
  purpose:
    "This is a tool for writers to look back on how their own document was written — not a way to police others.",
  tabChart: "Chart",
  tabFlow: "Flow",
  tabHighlights: "Highlights",
  tabSettings: "Settings",
  gap: "Split sessions at idle gaps over (hours)",
  from: "From",
  to: "To",
  bulkChars: "Bulk insertion (chars)",
  bulkCharsByRules: "Set by the rules file",
  bucket: "Time step",
  bucketAuto: "Auto",
  bucketMinute: "Minute",
  bucketHour: "Hour",
  bucketDay: "Day",
  chartSplit: "Split at idle gaps",
  saveSvg: "Save SVG",
  savePng: "Save PNG",
  saved: (p: string) => `Saved ${p}`,
  fixHistory: "Fix the settings (keeps a backup)",
  fixed: (p: string) => `Settings fixed. The original was kept as ${p}. Edits from now on will be timestamped.`,
  noFile: "No file opened",
  analyzing: "Analyzing…",
  highlightsEmpty: "No highlighted insertions in this document.",
  highlightsIntro:
    "Insertions picked out by the classifiers. Click one to show where it is in the figures. " +
    "These are hints for looking back, not proof of anything.",
  colWhen: "When",
  colCategory: "Category",
  colReason: "Why",
  colExcerpt: "Text",
  excerptDeleted: "(later deleted)",
  showInFlow: "Flow",
  showInChart: "Chart",
  settingsLang: "Language",
  langSystem: "System",
  settingsRules: "Highlight rules",
  rulesDefault: (n: number) => `Default (bulk insertion of ${n}+ chars at the same time)`,
  chooseRules: "Choose rules file…",
  clearRules: "Use the default",
  rulesError: (msg: string) => `The rules file can't be used: ${msg}`,
  settingsExtensions: "Extensions",
  extensionsNone: "No extensions are installed.",
  extensionsIntro:
    "Extensions add their own highlights, panels and dialogs. Only extensions bundled with the app are listed. " +
    "Each runs isolated, without access to your files or the network except through the permissions below.",
  extEnable: "Enabled",
  extStateActive: "Running",
  extStateStarting: "Starting…",
  extStateError: (msg: string) => `Error: ${msg}`,
  extPermissions: "Permissions",
  extPermNone: "No special permissions",
  extPermUi: (kinds: string) => `Show ${kinds}`,
  extPermStorage: "Keep its own data on this computer",
  extPermNetwork: (origins: string) => `Send data to ${origins}`,
  extPermText: "Read the document's text (inserted and deleted passages)",
  extConfirmTitle: (name: string) => `Enable "${name}"?`,
  extConfirmBody: "This extension asks for:",
  extConfirm: "Enable",
  cancel: "Cancel",
  ok: "OK",
  fromExtension: (name: string) => `From the extension "${name}"`,
  extPanels: "From extensions",
  formRequired: (label: string) => `"${label}" is required`,
  extClassifierFailed: (id: string, msg: string) => `The extension classifier ${id} failed: ${msg}`,
  sendConfirmTitle: "Send this data?",
  sendConfirmBody: (origin: string) =>
    `The extension wants to send the following data to ${origin}. Check it before sending. Nothing is sent if you decline.`,
  sendTo: "Destination",
  sendData: "Data (JSON)",
  sendAllow: "Send",
  sendDecline: "Don't send",
  extConfirmSends: "Ask before each send",
  extSendLog: "Send history",
  sendLogTitle: (name: string) => `Send history — ${name}`,
  sendLogEmpty: "Nothing has been sent.",
  sendLogNote: "Every send by this extension is recorded here, including declined and blocked ones (latest 500).",
  sendStatus: {
    sent: "Sent",
    failed: "Sent (error response)",
    rejected: "Declined by you",
    blocked: "Blocked (destination not declared)",
    queued: "Queued (offline)",
    discarded: "Discarded (extension disabled)",
    opened: "Link opened",
  } as Record<string, string>,
  close: "Close",
  openUrl: "Open from URL…",
  urlDialogTitle: "Open from OneDrive / SharePoint",
  urlDialogHelp:
    "Paste the link to a .docx on OneDrive or SharePoint. In Word or OneDrive, use Share → Copy link (the address of " +
    "the file also works). The document is downloaded into memory for analysis only.",
  urlPlaceholder: "https://…sharepoint.com/… or https://1drv.ms/…",
  urlOpen: "Open",
  urlRecent: "Recently opened",
  urlRecentEmpty: "Nothing opened from a URL yet.",
  urlRemove: "Remove from the list",
  urlOpening: "Opening… If your browser asks you to sign in to Microsoft, finish there and come back.",
  urlSignedInAs: (name: string) => `Signed in to Microsoft as ${name}.`,
  urlNotSignedIn: "Not signed in. The first time, you'll sign in to Microsoft in your browser.",
  signOut: "Sign out",
  urlNotConfigured:
    "Opening from OneDrive / SharePoint isn't set up in this copy of the app (no Microsoft application ID). " +
    "See Settings → Microsoft account.",
  urlErrors: {
    notConfigured: "Opening from OneDrive / SharePoint isn't set up (no Microsoft application ID).",
    badUrl: "This isn't a OneDrive or SharePoint address. Copy the link with Share → Copy link in Word or OneDrive.",
    notDocx: "The link points to something other than a .docx file.",
    notFound:
      "The file couldn't be found. If you copied the address of Word for the web, use Share → Copy link instead.",
    forbidden:
      "You don't have access to this file with the signed-in account, or your organization doesn't allow this app. " +
      "Try signing out and signing in with the right account.",
    tooLarge: "The file is too large (over 200 MB).",
    signInCancelled: "Sign-in wasn't completed.",
    network: "Couldn't reach OneDrive / SharePoint.",
  } as Record<string, string>,
  settingsMicrosoft: "Microsoft account (OneDrive / SharePoint)",
  msNotConfigured: "Not set up: enter the application (client) ID below.",
  msAdvanced: "Application (client) ID",
  msClientHelp:
    "The ID of the app registered in Microsoft Entra ID (Azure) for opening files from OneDrive / SharePoint. " +
    "Usually built into the app; set it here only if your organization registered its own.",
  save: "Save",
  cloudFixHint:
    "This document is on OneDrive / SharePoint, so the app can't change its settings. Open it in Word to change them, " +
    "or download it and open the downloaded file here.",
  openConfirmTitle: "Open this link?",
  openConfirmBody: (origin: string) =>
    `The extension wants to open the following address in your browser (${origin}). A link can carry data in its address, so check it first.`,
  openAllow: "Open",
  openDecline: "Don't open",
  figureOpenLink: (origin: string) => `Open ${origin} ↗`,
  figureAnnotated: "Annotated by an extension",
  figureAnnotatorFailed: (id: string, msg: string) => `The extension annotator ${id} failed: ${msg}`,
  integrityTitle: "About this document's history (informational)",
  integrityNotAvailable: "not recorded",
  integrityObserved: "differs from Word's usual output",
  integrityOk: "as usual",
  settingsUpdates: "Updates",
  checkForUpdates: "Check GitHub Releases for a new version at startup",
  updatesNote:
    "Only the app version is checked; no document or analysis data is sent. Updates are verified before installing.",
  updatesDevBuild: "Not available when running from source.",
  settingsAbout: "About",
  aboutText:
    "Track Changes in a .docx saved on a computer can be turned off, accepted, or rewritten (including dates and " +
    "authors), so the history shown here can be incomplete or altered. Use it to reflect on your own writing.",
  version: (v: string) => `Version ${v}`,
  error: (msg: string) => `Error: ${msg}`,
};

export type Strings = typeof en;

const ja: Strings = {
  appTitle: "Docx Revision Analyzer",
  open: ".docx を開く…",
  dropHere: "Word ファイル (.docx) をここにドロップするか、",
  dropHint: "解析はすべてこのコンピュータの中で行います。文書や本文をどこかへ送ることはありません。",
  purpose: "書き手が自分の文書の執筆過程を振り返るための道具です。他人を取り締まるためのものではありません。",
  tabChart: "チャート",
  tabFlow: "フロー",
  tabHighlights: "ハイライト",
  tabSettings: "設定",
  gap: "区間を分ける無編集期間 (時間)",
  from: "開始",
  to: "終了",
  bulkChars: "一括挿入 (文字数)",
  bulkCharsByRules: "ルールファイルで設定",
  bucket: "時間の刻み",
  bucketAuto: "自動",
  bucketMinute: "分",
  bucketHour: "時間",
  bucketDay: "日",
  chartSplit: "無編集期間で分ける",
  saveSvg: "SVG を保存",
  savePng: "PNG を保存",
  saved: (p) => `${p} に保存しました`,
  fixHistory: "設定を修正する (元のファイルは残します)",
  fixed: (p) => `設定を修正しました。元のファイルは ${p} として残しています。これからの編集には日時が記録されます。`,
  noFile: "ファイルが開かれていません",
  analyzing: "解析中…",
  highlightsEmpty: "この文書にはハイライトされた挿入はありません。",
  highlightsIntro:
    "分類器が取り上げた挿入です。クリックすると図の中の位置を示します。振り返りのための手がかりであり、何かの証拠ではありません。",
  colWhen: "日時",
  colCategory: "分類",
  colReason: "理由",
  colExcerpt: "本文",
  excerptDeleted: "(後で削除)",
  showInFlow: "フロー",
  showInChart: "チャート",
  settingsLang: "表示言語",
  langSystem: "システムに合わせる",
  settingsRules: "ハイライトの判定ルール",
  rulesDefault: (n) => `既定 (同じ時刻にまとめて ${n} 文字以上の挿入を一括挿入とする)`,
  chooseRules: "ルールファイルを選ぶ…",
  clearRules: "既定に戻す",
  rulesError: (msg) => `ルールファイルを使えません: ${msg}`,
  settingsExtensions: "拡張機能",
  extensionsNone: "インストールされている拡張機能はありません。",
  extensionsIntro:
    "拡張機能は、独自のハイライト・パネル・ダイアログを追加します。アプリに同梱された拡張機能だけを表示します。" +
    "拡張機能は隔離された環境で動き、下に示す権限の範囲でしかファイルやネットワークを使えません。",
  extEnable: "有効にする",
  extStateActive: "動作中",
  extStateStarting: "起動中…",
  extStateError: (msg) => `エラー: ${msg}`,
  extPermissions: "権限",
  extPermNone: "特別な権限はありません",
  extPermUi: (kinds) => `${kinds} を表示する`,
  extPermStorage: "このコンピュータに自分のデータを保存する",
  extPermNetwork: (origins) => `${origins} へデータを送る`,
  extPermText: "文書の本文 (挿入・削除された文章) を読む",
  extConfirmTitle: (name) => `「${name}」を有効にしますか?`,
  extConfirmBody: "この拡張機能は次の権限を求めています:",
  extConfirm: "有効にする",
  cancel: "キャンセル",
  ok: "OK",
  fromExtension: (name) => `拡張機能「${name}」より`,
  extPanels: "拡張機能より",
  formRequired: (label) => `「${label}」を入力してください`,
  extClassifierFailed: (id, msg) => `拡張機能の分類器 ${id} が失敗しました: ${msg}`,
  sendConfirmTitle: "このデータを送信しますか?",
  sendConfirmBody: (origin) =>
    `拡張機能が次のデータを ${origin} へ送ろうとしています。送信する前に内容を確認してください。送信しない場合は何も送られません。`,
  sendTo: "宛先",
  sendData: "データ (JSON)",
  sendAllow: "送信する",
  sendDecline: "送信しない",
  extConfirmSends: "送信の前に毎回確認する",
  extSendLog: "送信履歴",
  sendLogTitle: (name) => `送信履歴 — ${name}`,
  sendLogEmpty: "まだ何も送信していません。",
  sendLogNote: "この拡張機能による送信は、拒否・ブロックしたものも含めてすべてここに記録します (最新 500 件)。",
  sendStatus: {
    sent: "送信済み",
    failed: "送信済み (エラーの応答)",
    rejected: "拒否 (あなたが送信しなかった)",
    blocked: "ブロック (宣言されていない宛先)",
    queued: "キュー (オフライン)",
    discarded: "破棄 (拡張機能を無効にした)",
    opened: "リンクを開いた",
  },
  close: "閉じる",
  openUrl: "URL から開く…",
  urlDialogTitle: "OneDrive / SharePoint から開く",
  urlDialogHelp:
    "OneDrive や SharePoint 上の .docx のリンクを貼り付けてください。Word や OneDrive の「共有」→「リンクのコピー」で" +
    "コピーしたもの (ファイルのアドレスでも可) が使えます。文書は解析のためにメモリに読み込むだけです。",
  urlPlaceholder: "https://…sharepoint.com/… または https://1drv.ms/…",
  urlOpen: "開く",
  urlRecent: "最近開いた文書",
  urlRecentEmpty: "まだ URL から開いた文書はありません。",
  urlRemove: "一覧から削除",
  urlOpening: "読み込み中… ブラウザで Microsoft へのサインインを求められたら、サインインしてからアプリに戻ってください。",
  urlSignedInAs: (name) => `Microsoft に ${name} としてサインインしています。`,
  urlNotSignedIn: "サインインしていません。初回はブラウザで Microsoft にサインインします。",
  signOut: "サインアウト",
  urlNotConfigured:
    "このアプリでは OneDrive / SharePoint から開く設定がされていません (Microsoft のアプリケーション ID がありません)。" +
    "設定 → Microsoft アカウントを確認してください。",
  urlErrors: {
    notConfigured: "OneDrive / SharePoint から開く設定がされていません (Microsoft のアプリケーション ID がありません)。",
    badUrl: "OneDrive / SharePoint のアドレスではありません。Word や OneDrive の「共有」→「リンクのコピー」でコピーしてください。",
    notDocx: "リンク先が .docx ファイルではありません。",
    notFound: "ファイルが見つかりません。Word for the web のアドレスをコピーした場合は、「共有」→「リンクのコピー」を使ってください。",
    forbidden:
      "サインインしているアカウントではこのファイルにアクセスできないか、組織がこのアプリを許可していません。" +
      "サインアウトして、正しいアカウントでサインインし直してください。",
    tooLarge: "ファイルが大きすぎます (200 MB 超)。",
    signInCancelled: "サインインが完了しませんでした。",
    network: "OneDrive / SharePoint に接続できませんでした。",
  },
  settingsMicrosoft: "Microsoft アカウント (OneDrive / SharePoint)",
  msNotConfigured: "未設定: 下にアプリケーション (クライアント) ID を入力してください。",
  msAdvanced: "アプリケーション (クライアント) ID",
  msClientHelp:
    "OneDrive / SharePoint から開くために Microsoft Entra ID (Azure) に登録したアプリの ID です。通常はアプリに組み込まれています。" +
    "組織が独自に登録した場合だけ、ここで指定してください。",
  save: "保存",
  cloudFixHint:
    "この文書は OneDrive / SharePoint 上にあるため、アプリからは設定を変更できません。Word で開いて変更するか、" +
    "ダウンロードしたファイルをこのアプリで開いてください。",
  openConfirmTitle: "このリンクを開きますか?",
  openConfirmBody: (origin) =>
    `拡張機能が次のアドレスをブラウザで開こうとしています (${origin})。リンクのアドレスにはデータを含められるため、開く前に確認してください。`,
  openAllow: "開く",
  openDecline: "開かない",
  figureOpenLink: (origin) => `${origin} を開く ↗`,
  figureAnnotated: "拡張機能による注釈あり",
  figureAnnotatorFailed: (id, msg) => `拡張機能の注釈 ${id} が失敗しました: ${msg}`,
  integrityTitle: "この文書の履歴について (情報)",
  integrityNotAvailable: "記録なし",
  integrityObserved: "Word の通常の形と違う点あり",
  integrityOk: "通常どおり",
  settingsUpdates: "アップデート",
  checkForUpdates: "起動時に GitHub Releases で新しいバージョンを確認する",
  updatesNote: "確認するのはアプリのバージョンだけで、文書や解析結果は送りません。更新は検証してから入れ替えます。",
  updatesDevBuild: "ソースから起動している場合は使えません。",
  settingsAbout: "このアプリについて",
  aboutText:
    "コンピュータに保存された .docx の変更履歴は、記録をオフにする・すべて承諾する・日時や作成者を書き換えるといった操作で" +
    "消したり作り替えたりできます。ここに表示される履歴は欠けていたり改変されていたりする可能性があります。" +
    "自分の執筆を振り返るために使ってください。",
  version: (v) => `バージョン ${v}`,
  error: (msg) => `エラー: ${msg}`,
};

export const STRINGS: Record<AppLang, Strings> = { en, ja };
